In [106]:
#1.numpy数组与python列表效率对比
import numpy as np 
import numpy.random as rand
arr = np.arange(1e7)
larr = arr.tolist()
def list_times(alist, scalar):
    for i,val in enumerate(alist):
        alist[i]=val*scalar
    return alist
#timeit 计算运行时间 timeitarr*1.1
list_times(larr,1.1)

[0.0,
 1.1,
 2.2,
 3.3000000000000003,
 4.4,
 5.5,
 6.6000000000000005,
 7.700000000000001,
 8.8,
 9.9,
 11.0,
 12.100000000000001,
 13.200000000000001,
 14.3,
 15.400000000000002,
 16.5,
 17.6,
 18.700000000000003,
 19.8,
 20.900000000000002,
 22.0,
 23.1,
 24.200000000000003,
 25.3,
 26.400000000000002,
 27.500000000000004,
 28.6,
 29.700000000000003,
 30.800000000000004,
 31.900000000000002,
 33.0,
 34.1,
 35.2,
 36.300000000000004,
 37.400000000000006,
 38.5,
 39.6,
 40.7,
 41.800000000000004,
 42.900000000000006,
 44.0,
 45.1,
 46.2,
 47.300000000000004,
 48.400000000000006,
 49.50000000000001,
 50.6,
 51.7,
 52.800000000000004,
 53.900000000000006,
 55.00000000000001,
 56.1,
 57.2,
 58.300000000000004,
 59.400000000000006,
 60.50000000000001,
 61.60000000000001,
 62.7,
 63.800000000000004,
 64.9,
 66.0,
 67.10000000000001,
 68.2,
 69.30000000000001,
 70.4,
 71.5,
 72.60000000000001,
 73.7,
 74.80000000000001,
 75.9,
 77.0,
 78.10000000000001,
 79.2,
 80.30000000000001,
 81.4,
 82

In [13]:
#2.创建数组并设置数据类型
#(1)从列表转换
alist = [1, 2, 3]
arr = np.array(alist)
#(2)np.arange()
arr = np.arange(100)
arr = np.arange(10, 100)
#(3)np.zeros()
arr = np.zeros(5)
np.zeros((5,5))
cube = np.zeros((5,5,5)).astype(int)+1
cube = np.ones((5,5,5)).astype(np.float16)
arr = np.zeros(2, dtype=int)
arr = np.zeros(2, dtype=np.float32)
#(4)reshape()
arr1d = np.arange(1000)
arr3d = arr1d.reshape((10,10,10))
arr3d = np.reshape(arr1d, (10,10,10))
#(5)revel
#作用于reshape相反
#(6)shape显示数据对象的形状
print(arr1d.shape)

(1000,)


In [47]:
#3.记录数组 
#(1)创建记录数组并赋值
# 创建大小为2的记录数组，类型为4字节整数、4字节浮点数和10字节字符 
recarr = np.zeros((2,),dtype=('i4, f4, a10'))
#print(recarr)
recarr[:] = [(1,2., 'Hello'),(2,3., 'World')]
print(recarr)
#(2)使用zip
recarr = np.zeros((2,),dtype=('i4, f4, a10'))
col1 = np.arange(2)+1
col2 = np.arange(2, dtype=np.float32)
col3 = ['Hello', 'World']
print(col1,col2, col3)
k = zip(col1,col2,col3)
#recarr[:] = zip(col1, col2, col3)
print(k)
#(3)为每列数据命名
recarr.dtype.names=('Integers','Floats','Strings')
#(4)使用列名访问数据
#recarr('Integers')

[(1, 2., b'Hello') (2, 3., b'World')]
[1 2] [0. 1.] ['Hello', 'World']


In [64]:
#4.索引和切片
#(1)numpy提供了类似于matlab的索引和切片 
alist = [[1,2], [3,4]]
alist[0][1]
arr = np.array(alist)
print(arr)
print("第0行第1列",arr[0,1])
print("第1列",arr[:,1])
print("第1行",arr[:,1])
#(2)np.where()
index = np.where(arr>2)
new_arr = arr[index]
new_arr = np.delete(arr,index)
print(new_arr)
print(arr)

[[1 2]
 [3 4]]
第0行第1列 2
第1列 [2 4]
第1行 [2 4]
[3 4]
[[1 2]
 [3 4]]


In [93]:
#5.Numpy数组的布尔操作
#Plot A
img1 = np.zeros((20,20))+3
img1[4:-4, 4:-4]=6
img1[7:-7, 7:-7]=9
print("Plot A")
print(img1)
index1 = img1>3
index2 = img1<7
compound_index =index1&index2
#compound_index =(img1>3)&(img1<7)
#Plot B
img2 = np.copy(img1)
img2[compound_index]=0
print("Plot B")
print(img2)
#Plot C
index3 = img1 == 9
index4 = (img1 == 3)|index3
img3 = np.copy(img1)
img3[index4]=0
print("Plot C")
print(img3)
#例子
#产生一个随机分布的正态函数
a = rand.randn(100) 
print(a)
index = a > 0.2 
b = a[index] 
print(b)
def suqare(num):
    return num*num
b = list(map(suqare,b))
print(b)

Plot A
[[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 9. 9. 9. 9. 9. 9. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 9. 9. 9. 9. 9. 9. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 9. 9. 9. 9. 9. 9. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 9. 9. 9. 9. 9. 9. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 9. 9. 9. 9. 9. 9. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 9. 9. 9. 9. 9. 9. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 3. 3. 3. 3.]
 [3. 3. 3. 3. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6

In [105]:
#6.读写操作
#(1)Python读写文本文件
f = open("novel.txt", "r", encoding="utf-8")
alist = f.readlines()
print(alist)
f.close()
f1 = open("Helloworld.txt", "w", encoding="utf-8")
f1.writelines("Hello World!")
f1.close()

['\ufeff我与地坛\n', '史铁生\n', '一\n', '我在好几篇小说中都提到过一座废弃的古园，实际就是地坛。许多年前旅游业还没有开展，园子荒芜冷落得如同一片野地，很少被人记起。\n', '地坛离我家很近。或者说我家离地坛很近。总之，只好认为这是缘分。地坛在我出生前四百多年就座落在那儿了，而自从我的祖母年轻时带着我父亲来到北京，就一直住在离它不远的地方一五十多年间搬过几次家，可搬来搬去总是在它周围，而且是越搬离它越近了。我常觉得这中间有着宿命的味道：仿佛这古园就是为了等我，而历尽沧桑在那儿等待了四百多年。\n', '它等待我出生，然后又等待我活到最狂妄的年龄上忽地残废了双腿。四百多年里，它一面剥蚀了古殿檐头浮夸的琉璃，淡褪了门壁上炫耀的朱红，坍圮了一段段高墙又散落了玉砌雕栏，祭坛四周的老柏树愈见苍幽，到处的野草荒藤也都茂盛得自在坦荡。这时候想必我是该来了。十五年前的一个下午，我摇着轮椅进入园中，它为一个失魂落魄的人把一切都准备好了。那时，太阳循着亘古不变的路途正越来越大，也越红。在满园弥漫的沉静光芒中，一个人更容易看到时间，并看见自己的身影。\n', '自从那个下午我无意中进了这园子，就再没长久地离开过它。我一下子就理解了它的意图。正如我在一篇小说中所说的："在人口密聚的城市里，有这样一个宁静的去处，像是上帝的苦心安排。"\n', '两条腿残废后的最初几年，我找不到工作，找不到去路，忽然间几乎什么都找不到了，我就摇了轮椅总是到它那儿去，仅为着那儿是可以逃避一个世界的另一个世界。我在那篇小说中写道："没处可去我便一天到晚耗在这园子里。跟上班下班一样，别人去上班我就摇了轮椅到这儿来。园子无人看管，上下班时间有些抄近路的人们从园中穿过，园子里活跃一阵，过后便沉寂下来。""园墙在金晃晃的空气中斜切下一溜荫凉，我把轮椅开进去，把椅背放倒，坐着或\u3000是躺着，看书或者想事，撅一杈树枝左右拍打，驱赶那些和我一样不明白为什么要来这世上的小昆虫。""蜂儿如一朵小雾稳稳地停在半空；蚂蚁摇头晃脑捋着触须，猛然间想透了什么，转身疾行而去；瓢虫爬得不耐烦了，累了祈祷一回便支开翅膀，忽悠一下升空了；树干上留着一只蝉蜕，寂寞如一间空屋；露水在草叶上滚动、聚集，压弯了草叶轰然坠地摔开万道金光。""满园子都是草木竞相生长弄出的响动，窸窸窣窣窸窸窣窣片刻不息。"这都是真实的记录，园子

In [153]:
#(2)Numpy文件读写
arr1 = np.loadtxt('Number.txt', encoding="utf-8")
print(type(arr1))
arr1 = np.array(arr1,np.float32)
arr2, arr3 = arr1*2, arr1*3
print(arr1, arr2, arr3)
np.savetxt('NewNumber.txt', (arr1, arr2, arr3), encoding="utf-8")
#例子
# table = np.loadtxt('DataTable.txt', dtype='names':('ID','Result','Type'),
#                    'formats':('S4','f4','i2'), encoding="utf-8")

<class 'numpy.ndarray'>
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.] [ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]


In [154]:
#(3)二进制文件
data = np.empty((1000, 1000))
np.save('test.npy', data)
np.savez('test.npz', data)
newdata = np.load('test.npy')
#NumPy使用numpy.save和numpy.load来读写二进制文件，但这种二进制文件 只能在NumPy下读写
#scipy.io可以处理更通用的二进制文件 

In [156]:
#7.数学运算
#使用 numpy.dot 和 numpy.transpose 分别来进行矩阵乘法运算和矩阵转置
A = np.matrix([[3,6,-5], [1, -3, 2], [5, -1, 4]])
B = np.matrix([[12],[-2],[10]])
print(A)
print(B)
X = A*(-1)*B
print(X)
#使用数组解方程组
print("使用数组解方程组")
a = np.array([[3,6,-5],[1,-3,2],[5,-1,4]])
b = np.array([12,-2,10])
print(a)
print(b)
x = np.dot(a,np.transpose(b))
print(x)

[[ 3  6 -5]
 [ 1 -3  2]
 [ 5 -1  4]]
[[12]
 [-2]
 [10]]
[[  26]
 [ -38]
 [-102]]
使用数组解方程组
[[ 3  6 -5]
 [ 1 -3  2]
 [ 5 -1  4]]
[12 -2 10]
[-26  38 102]
