In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [127]:
#1.Pandas库总体说明
#(1)Series
#自动生成索引
Series1 = pd.Series(np.random.randn(4))
print("第一个序列\n", Series1)
print("\nSeries1<0\n", Series1<0)
print("\nSeries1[Series1<0]\n", Series1[Series1<0])
#修改索引
Series2 = pd.Series(Series1.values, index = ["row_" + str(i) for i in range(4)])
print("\n第二个序列\n", Series2)
#Python的基础数据结构字典也可以转化为Series
Series3 = pd.Series({"China":"Beijing","England":"GB","Japan":"Tokyo"})
print("\n第三个序列\n", Series3)
#如果需要字典的顺序不变
Series4_IndexList = ["China","Japan","England"]
Series4 = pd.Series(Series3, index=Series4_IndexList)
print("\n第四个序列\n", Series4)
#index允许重复，但是这样容易导致错误
Series5_IndexList = ["A","B","C","C"]
Series5 = pd.Series(Series1, index=Series5_IndexList)
print("\n第五个序列\n", Series5)

第一个序列
 0    0.658962
1   -0.630648
2    1.639458
3   -0.320019
dtype: float64

Series1<0
 0    False
1     True
2    False
3     True
dtype: bool

Series1[Series1<0]
 1   -0.630648
3   -0.320019
dtype: float64

第二个序列
 row_0    0.658962
row_1   -0.630648
row_2    1.639458
row_3   -0.320019
dtype: float64

第三个序列
 China      Beijing
England         GB
Japan        Tokyo
dtype: object

第四个序列
 China      Beijing
Japan        Tokyo
England         GB
dtype: object

第五个序列
 A   NaN
B   NaN
C   NaN
C   NaN
dtype: float64


In [128]:
#(1)DataFrame
#DataFrame可以视作Series的有序集合， 可以从数据库、NumPy二维数组、JSON中定义数据框
#NumPy二维数组
DF1 = pd.DataFrame(np.asarray([("Japan", "Tokyo", 4000), ("S.Korea", "Seoul", 1000), ("China", "Beijing", 9000)]),
                   columns = ["nation", "capital", "GDP"])
print("DF1\n", DF1)
#JSON
DF2 = pd.DataFrame({"nation": ["Japan", "S.Korea", "China"], "capital": ["Tokyo", "Seoul", "Beijing"], "GDP": [4000, 1000, 9000]})
print("\nDF2\n", DF2)
#使其顺序不变
DF3 = pd.DataFrame(DF2, columns = ["nation", "capital", "GDP"])
print("\nDF3\n", DF3)
#人为指定行标秩序
DF4 = pd.DataFrame(DF2, columns = ["nation", "capital", "GDP"], index = [2, 0, 1])
print("\nDF4\n", DF4)
#在DataFrame中切片
#取列：推荐使用DF4["GDP"]，最好别用DF4.GDP
#取行：DF4[0: 1]或者DF4.ix[0]
print("\n取列\n",DF4["nation"])
print("\n取行\n",DF4[0:2])
#动态增加列
DF4["region"] = "East Asian"
print("\nDF4\n", DF4)

DF1
     nation  capital   GDP
0    Japan    Tokyo  4000
1  S.Korea    Seoul  1000
2    China  Beijing  9000

DF2
     nation  capital   GDP
0    Japan    Tokyo  4000
1  S.Korea    Seoul  1000
2    China  Beijing  9000

DF3
     nation  capital   GDP
0    Japan    Tokyo  4000
1  S.Korea    Seoul  1000
2    China  Beijing  9000

DF4
     nation  capital   GDP
2    China  Beijing  9000
0    Japan    Tokyo  4000
1  S.Korea    Seoul  1000

取列
 2      China
0      Japan
1    S.Korea
Name: nation, dtype: object

取行
   nation  capital   GDP
2  China  Beijing  9000
0  Japan    Tokyo  4000

DF4
     nation  capital   GDP      region
2    China  Beijing  9000  East Asian
0    Japan    Tokyo  4000  East Asian
1  S.Korea    Seoul  1000  East Asian


In [129]:
#1.代表性函数的使用介绍
#一、创建对象
#(1)通过传递一个list对象来创建一个Series
s = pd.Series([1,3,5,np.nan,6,8])
print(s)
#(2)通过传递一个numpy array，时间索引以及列标签来创建一个DataFrame
dates = pd.date_range('20130101',periods=6)
print(dates)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
print("\ndf\n",df)
#(3)通过传递一个能够被转换成类似序列结构的字典对象来创建一个DataFrame
df2 = pd.DataFrame({ 'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo' })
print("\ndf2\n",df2)
print("\ndf2\n",df2.dtypes)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

df
                    A         B         C         D
2013-01-01  0.248387 -0.937184 -1.460727  0.552644
2013-01-02 -0.047800  0.317855 -0.729493 -0.980301
2013-01-03 -0.266653  0.880885 -0.308791 -0.795262
2013-01-04  1.153541 -0.078806 -0.021827 -1.840917
2013-01-05 -0.915201  0.655576  0.426462  0.270356
2013-01-06 -1.602181 -0.691604  0.971885  0.208400

df2
      A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

df2
 A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [130]:
#二、查看数据
#(1)查看frame中头部和尾部的行
#默认是前5行数据
print("前5行数据\n", df.head())
#查看倒数第几条数据
print("\n后3行数据\n", df.tail(3))
#(2)显示索引、列和底层的numpy数据
print("\n索引\n", df.index)
print("\n列\n", df.columns)
print("\n底层的numpy数据\n", df.values)
#(3)describe()函数对于数据的快速统计汇总
df.describe()
print("\n快速统计汇总\n", df.describe())
#(4)对数据的转置
print("\n对数据的转置\n", df.T)
#(5)按轴进行排序
print("\n按轴进行排序\n", df.sort_index(axis=1, ascending=False))
#(5)按值进行排序
print("\n按值进行排序\n", df.sort_values(by='B'))

前5行数据
                    A         B         C         D
2013-01-01  0.248387 -0.937184 -1.460727  0.552644
2013-01-02 -0.047800  0.317855 -0.729493 -0.980301
2013-01-03 -0.266653  0.880885 -0.308791 -0.795262
2013-01-04  1.153541 -0.078806 -0.021827 -1.840917
2013-01-05 -0.915201  0.655576  0.426462  0.270356

后3行数据
                    A         B         C         D
2013-01-04  1.153541 -0.078806 -0.021827 -1.840917
2013-01-05 -0.915201  0.655576  0.426462  0.270356
2013-01-06 -1.602181 -0.691604  0.971885  0.208400

索引
 DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

列
 Index(['A', 'B', 'C', 'D'], dtype='object')

底层的numpy数据
 [[ 0.24838708 -0.93718383 -1.46072702  0.55264432]
 [-0.04779962  0.31785515 -0.72949305 -0.98030072]
 [-0.26665271  0.88088457 -0.3087911  -0.79526235]
 [ 1.15354084 -0.07880578 -0.0218271  -1.84091674]
 [-0.91520138  0.65557649  0.42646218  0.2

In [131]:
#三、选择
#(1)选择一个单独的列，这将会返回一个Series，等同于df.A
print("选择一个单独的列\n", df['A'])
#(2)通过[]进行选择，这将会对行进行切片
print("\n通过[]进行选择\n", df[0:3])
#(3)使用标签来获取一个交叉的区域
print("\n使用标签来获取一个交叉的区域\n", df.loc[[dates[0]]])
#(4)通过标签来在多个轴上进行选择
print("\n通过标签来在多个轴上进行选择\n", df.loc[:,['A','B']])
#(5)标签切片
print("\n标签切片\n", df.loc['20130102':'20130104',['A','B']])
#(6)对于返回的对象进行维度缩减
print("\n对于返回的对象进行维度缩减\n", df.loc['20130102',['A','B']])
#(7)获取一个标量
print("\n获取一个标量\n", df.loc[dates[0],'A'])
#(8)快速访问一个标量
print("\n快速访问一个标量\n", df.at[dates[0],'A'])
#(9)通过传递数值进行位置选择（选择的是行）
print("\n通过传递数值进行位置选择\n", df.iloc[3])
#(10)通过数值进行切片
print("\n通过数值进行切片\n", df.iloc[3:5,0:2])
#(11)通过指定一个位置的列表
print("\n通过指定一个位置的列表\n", df.iloc[[1,2,4],[0,2]])
#(12)对行进行切片
print("\n对行进行切片\n", df.iloc[1:3,:])
#(13)对列进行切片
print("\n对列进行切片\n", df.iloc[:,1:3])
#(14)获取特定的值
print("\n获取特定的值\n",(df.iloc[1,1],df.iat[1,1]))
#(15)使用一个单独列的值来选择数据
print("\n使用一个单独列的值来选择数据\n", df[df.A > 0])
#(16)选择数据
print("\n选择数据\n", df[df > 0])
#(17)使用isin()方法来过滤
df2 = df.copy()
df2['E']=['one', 'one','two','three','four','three']
print("\n使用isin()方法来过滤\n", df2)
print("\n使用isin()方法来过滤\n", df2[df2['E'].isin(['two','four'])])

#设置
#(1)设置一个新的列
s1 = pd.Series([1,2,3,4,5,6],index = pd.date_range('20130102',periods=6))
print("\n设置一个新的列\n", s1)
#(2)通过标签设置新的值
df.at[dates[0],'A']=0
print("\n通过标签设置新的值\n", df)
#(3)通过位置设置新的值
df.iat[0,1] = 0
print("\n通过位置设置新的值\n", df)
#(4)通过一个numpy数组设置一组新值
df.loc[:,'D'] = np.array([5] * len(df))
print("\n通过一个numpy数组设置一组新值\n", df)
#(5)通过where操作来设置新的值
df2 = df.copy()
df2[df2 > 0] =-df2
print("\n通过where操作来设置新的值\n", df2)

选择一个单独的列
 2013-01-01    0.248387
2013-01-02   -0.047800
2013-01-03   -0.266653
2013-01-04    1.153541
2013-01-05   -0.915201
2013-01-06   -1.602181
Freq: D, Name: A, dtype: float64

通过[]进行选择
                    A         B         C         D
2013-01-01  0.248387 -0.937184 -1.460727  0.552644
2013-01-02 -0.047800  0.317855 -0.729493 -0.980301
2013-01-03 -0.266653  0.880885 -0.308791 -0.795262

使用标签来获取一个交叉的区域
                    A         B         C         D
2013-01-01  0.248387 -0.937184 -1.460727  0.552644

通过标签来在多个轴上进行选择
                    A         B
2013-01-01  0.248387 -0.937184
2013-01-02 -0.047800  0.317855
2013-01-03 -0.266653  0.880885
2013-01-04  1.153541 -0.078806
2013-01-05 -0.915201  0.655576
2013-01-06 -1.602181 -0.691604

标签切片
                    A         B
2013-01-02 -0.047800  0.317855
2013-01-03 -0.266653  0.880885
2013-01-04  1.153541 -0.078806

对于返回的对象进行维度缩减
 A   -0.047800
B    0.317855
Name: 2013-01-02 00:00:00, dtype: float64

获取一个标量
 0.24838708477396346

快速访问

In [132]:
#四、缺失值处理
#(1)使用reindex
df1 = df.reindex(index=dates[0:4], columns=list(df.columns)+['E'])
df1.loc[dates[0]:dates[1],'E']=1
print("\n使用reindex\n", df1)
#(2)去掉包含缺失值的行
print("\n去掉包含缺失值的行\n", df1.dropna(how='any'))
#(3)对缺失值进行填充
print("\n对缺失值进行填充\n", df1.fillna(value=5))
#(4)对数据进行布尔填充
print("\n对数据进行布尔填充\n", pd.isnull(df1))


使用reindex
                    A         B         C  D    E
2013-01-01  0.000000  0.000000 -1.460727  5  1.0
2013-01-02 -0.047800  0.317855 -0.729493  5  1.0
2013-01-03 -0.266653  0.880885 -0.308791  5  NaN
2013-01-04  1.153541 -0.078806 -0.021827  5  NaN

去掉包含缺失值的行
                  A         B         C  D    E
2013-01-01  0.0000  0.000000 -1.460727  5  1.0
2013-01-02 -0.0478  0.317855 -0.729493  5  1.0

对缺失值进行填充
                    A         B         C  D    E
2013-01-01  0.000000  0.000000 -1.460727  5  1.0
2013-01-02 -0.047800  0.317855 -0.729493  5  1.0
2013-01-03 -0.266653  0.880885 -0.308791  5  5.0
2013-01-04  1.153541 -0.078806 -0.021827  5  5.0

对数据进行布尔填充
                 A      B      C      D      E
2013-01-01  False  False  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-04  False  False  False  False   True


In [133]:
#五、统计
#执行描述性统计
print("\n执行描述性统计\n",(df.mean(),df.mean(1)))
#对于拥有不同维度，需要对齐的对象进行操作
s = pd.Series([1,3,5,np.nan,6,8],index=dates).shift(2)
print("\n对于拥有不同维度，需要对齐的对象进行操作\n",s)
#对数据应用函数
print("\n对数据应用函数\n",df.apply(np.cumsum))
print("\n对数据应用函数\n",df.apply(lambda x: x.max()-x.min()))
#直方图
s = pd.Series(np.random.randint(0,7,size=10))
print("\n直方图\n",(s,s.value_counts()))
#字符串方法
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
print("\n直方图\n",s.str.lower())


执行描述性统计
 (A   -0.279716
B    0.180651
C   -0.187082
D    5.000000
dtype: float64, 2013-01-01    0.884818
2013-01-02    1.135141
2013-01-03    1.326360
2013-01-04    1.513227
2013-01-05    1.291709
2013-01-06    0.919525
Freq: D, dtype: float64)

对于拥有不同维度，需要对齐的对象进行操作
 2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64

对数据应用函数
                    A         B         C   D
2013-01-01  0.000000  0.000000 -1.460727   5
2013-01-02 -0.047800  0.317855 -2.190220  10
2013-01-03 -0.314452  1.198740 -2.499011  15
2013-01-04  0.839089  1.119934 -2.520838  20
2013-01-05 -0.076113  1.775510 -2.094376  25
2013-01-06 -1.678294  1.083906 -1.122491  30

对数据应用函数
 A    2.755722
B    1.572489
C    2.432612
D    0.000000
dtype: float64

直方图
 (0    5
1    5
2    4
3    1
4    1
5    2
6    0
7    3
8    1
9    1
dtype: int32, 1    4
5    2
4    1
3    1
2    1
0    1
dtype: int64)

直方图
 0       a
1       b
2       c
3    aaba


In [134]:
#六、合并
#用concat()把pandas类合并到一起
df = pd.DataFrame(np.random.randn(10,4))
print(df)
pieces = [df[:3],df[3:7],df[7:]]
print(pd.concat(pieces))
#Join
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})
print(left)
print(right)
print(pd.merge(left, right, on='key'))
#Append 将一行连接到一个DataFrame上
df = pd.DataFrame(np.random.randn(8, 4), columns=['A','B','C','D'])
print(df)
s = df.iloc[3]
df.append(s, ignore_index=True)

          0         1         2         3
0 -0.243256 -0.215859  1.313307  0.740960
1 -0.326517  0.450050  1.510430  0.225855
2  0.268920 -0.005954 -0.577593  1.335955
3 -2.341901  0.112469  0.605596  0.824530
4 -0.521644 -0.459018  1.233752  0.050143
5  0.066279 -1.733981 -0.101652  0.368915
6 -0.463762 -0.101509 -0.528801 -1.221231
7  0.674300 -0.268682  0.433062  0.353924
8  0.018245 -0.320188 -0.323600 -0.619113
9 -0.511183 -0.558940 -0.252444 -0.454279
          0         1         2         3
0 -0.243256 -0.215859  1.313307  0.740960
1 -0.326517  0.450050  1.510430  0.225855
2  0.268920 -0.005954 -0.577593  1.335955
3 -2.341901  0.112469  0.605596  0.824530
4 -0.521644 -0.459018  1.233752  0.050143
5  0.066279 -1.733981 -0.101652  0.368915
6 -0.463762 -0.101509 -0.528801 -1.221231
7  0.674300 -0.268682  0.433062  0.353924
8  0.018245 -0.320188 -0.323600 -0.619113
9 -0.511183 -0.558940 -0.252444 -0.454279
   key  lval
0  foo     1
1  foo     2
   key  rval
0  foo     4
1  foo     

A         B         C         D
0 -1.350947 -1.227041 -0.761204 -1.198424
1 -0.769046 -0.615677 -0.374077  0.719150
2 -0.379165 -0.052717  0.637693 -0.218700
3  0.063701  0.360948  0.899658 -0.448981
4  0.121561 -0.210662  0.809399 -0.183768
5  0.561535 -0.729665  0.657494  0.119621
6  1.037683  1.693061 -1.248678 -0.432975
7 -0.247970 -1.004131 -0.657825 -0.246231
8  0.063701  0.360948  0.899658 -0.448981

In [135]:
#七、分组
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                           'foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three',
                          'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})
print(df)
#(1)分组并对每个分组执行sum函数
print("\n分组并对每个分组执行sum函数\n",df.groupby('A').sum())
#(2)通过多个列进行分组形成一个层次索引，然后执行函数
print("\n通过多个列进行分组形成一个层次索引\n",df.groupby(['A','B']).sum())
#Stack
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz',
                      'foo', 'foo', 'qux', 'qux'],
                     ['one', 'two', 'one', 'two',
                     'one', 'two', 'one', 'two']]))
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=['A', 'B'])
df2 = df[:4]
print(df2)
stacked = df2.stack()
print("\nstacked\n",stacked)
print(stacked.unstack())
print(stacked.unstack(1))
print(stacked.unstack(0))
#数据透视表
df = pd.DataFrame({'A' : ['one', 'one', 'two', 'three'] * 3,
                    'B' : ['A', 'B', 'C'] * 4,
                    'C' : ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'] * 2,
                    'D' : np.random.randn(12),
                    'E' : np.random.randn(12)})
print("\n创建数据集\n", df)
df1 = np.array(df)
#print(df1)
print("\n生成数据透视表\n", pd.pivot_table(df, values='D', index=['A', 'B'], columns=['C']))

     A      B         C         D
0  foo    one  0.031720  0.611435
1  bar    one  0.970641 -0.691284
2  foo    two  0.020435  0.292713
3  bar  three  1.316209  0.491299
4  foo    two -0.992874 -0.966333
5  bar    two  0.118049 -0.135551
6  foo    one  0.649456  0.609807
7  foo  three -1.690337  0.440472

分组并对每个分组执行sum函数
             C         D
A                      
bar  2.404899 -0.335536
foo -1.981599  0.988094

通过多个列进行分组形成一个层次索引
                   C         D
A   B                        
bar one    0.970641 -0.691284
    three  1.316209  0.491299
    two    0.118049 -0.135551
foo one    0.681176  1.221242
    three -1.690337  0.440472
    two   -0.972438 -0.673620
                     A         B
first second                    
bar   one    -0.100691 -0.390408
      two    -0.015286 -0.672990
baz   one    -0.024403 -1.007620
      two    -1.750916 -1.804564

stacked
 first  second   
bar    one     A   -0.100691
               B   -0.390408
       two     A   -0.015286
        

In [145]:
#九、导入和保存数据
#(1)写入CSV文件
df.to_csv('foo.csv')
print("写入CSV文件\n", pd.read_csv('foo.csv'))
#(2)写入HDF5(需要事先在命令行里 pip install --upgrade tables )
df.to_hdf('foo.h5','df')
print("\n写入HDF5\n", pd.read_hdf('foo.h5','df'))
#(3)写入excel文件(需要事先在命令行里 pip install openpyxl，pip install xlrd)
df.to_excel('foo.xlsx', sheet_name='Sheet1')
print("写入excel文件", pd.read_excel('foo.xlsx', 'Sheet1', index_col=None, na_values=['NA']))

写入CSV文件
     Unnamed: 0      A  B    C         D         E
0            0    one  A  foo  1.505455  0.495830
1            1    one  B  foo -1.039014  0.689856
2            2    two  C  foo  0.236746  0.689896
3            3  three  A  bar  0.079362  1.105964
4            4    one  B  bar  2.933005  0.234665
5            5    one  C  bar -0.070498  0.964271
6            6    two  A  foo  0.067905 -2.690069
7            7  three  B  foo  1.145574  0.088239
8            8    one  C  foo -1.916415  0.281726
9            9    one  A  bar -0.358477 -0.089002
10          10    two  B  bar  0.049325 -0.177672
11          11  three  C  bar -1.130230 -0.829983

写入HDF5
         A  B    C         D         E
0     one  A  foo  1.505455  0.495830
1     one  B  foo -1.039014  0.689856
2     two  C  foo  0.236746  0.689896
3   three  A  bar  0.079362  1.105964
4     one  B  bar  2.933005  0.234665
5     one  C  bar -0.070498  0.964271
6     two  A  foo  0.067905 -2.690069
7   three  B  foo  1.145574 